### ISSUE TITLE
Iam getting this error while sending an image 

### ISSUE THREAD

**Issue by venkataramkrishna** [bountysource/core#1542]
MongoError: file with id 2021-06-24T12:17:35.773Z-Provider Spotlight  not opened for writing     at Function.create (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/error.js:57:12)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:955:22     at executeCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:70:5)     at handleCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/utils.js:102:55)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/operations/find_one.js:29:9     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/utils.js:674:5     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:250:9     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:736:9     at handleCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:31:5)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:680:38     at Cursor._endSession (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:394:7)     at _setCursorNotifiedImpl (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:689:10)     at setCursorNotified (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:680:3)     at done (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:455:16)     at queryCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:500:20)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:545:9 Emitted 'error' event on GridReadStream instance at:     at GridReadStream._error (/var/www/html/socialapi/node_modules/gridfs-stream/lib/readstream.js:231:8)     at /var/www/html/socialapi/node_modules/gridfs-stream/lib/readstream.js:109:26     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/utils.js:385:14     at executeCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/utils.js:375:25)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:246:23     at error (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:1055:5)     at /var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/gridfs/grid_store.js:954:16     at executeCallback (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/operations/execute_operation.js:70:5)     [... lines matching original stack trace ...]     at Cursor._endSession (/var/www/html/socialapi/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:394:7) {​​​​​​​​   driver: true

**Comment by venkataramkrishna** [comment]
@antenore @BinaryFissionGames
